"""Initial migration from existing models

Revision ID: f0e5d07d8c05
Revises:
Create Date: 2025-12-03 05:13:34.517042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f0e5d07d8c05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)

    # Create agents table
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('faction', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.CheckConstraint('faction IN (\'Enlightened\', \'Resistance\')', name='check_faction'),
    sa.CheckConstraint('level >= 1', name='check_min_level'),
    sa.CheckConstraint('level <= 16', name='check_max_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name')
    )
    op.create_index('idx_agent_name', 'agents', ['agent_name'], unique=False)
    op.create_index('idx_faction', 'agents', ['faction'], unique=False)
    op.create_index('idx_user_agent', 'agents', ['user_id', 'agent_name'], unique=False)
    op.create_index(op.f('ix_agents_faction'), 'agents', ['faction'], unique=False)

    # Create stats_submissions table
    op.create_table('stats_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('submission_time', sa.Time(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.CheckConstraint('period_type IN (\'all_time\', \'monthly\', \'weekly\', \'daily\')', name='check_period_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'submission_date', 'period_type')
    )
    op.create_index(op.f('ix_stats_submissions_agent_id'), 'stats_submissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_stats_submissions_submission_date'), 'stats_submissions', ['submission_date'], unique=False)
    op.create_index(op.f('ix_stats_submissions_period_type'), 'stats_submissions', ['period_type'], unique=False)

    # Create agent_stats table
    op.create_table('agent_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stats_submission_id', sa.Integer(), nullable=False),
    sa.Column('stat_name', sa.String(length=100), nullable=False),
    sa.Column('stat_value', sa.BigInteger(), nullable=True),
    sa.Column('stat_rank', sa.Integer(), nullable=True),
    sa.Column('stat_category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['stats_submission_id'], ['stats_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stats_submission_id', 'stat_name')
    )
    op.create_index(op.f('ix_agent_stats_stat_category'), 'agent_stats', ['stat_category'], unique=False)
    op.create_index(op.f('ix_agent_stats_stat_name'), 'agent_stats', ['stat_name'], unique=False)
    op.create_index(op.f('ix_agent_stats_stats_submission_id'), 'agent_stats', ['stats_submission_id'], unique=False)

    # Create leaderboard_cache table
    op.create_table('leaderboard_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('faction_filter', sa.String(length=20), nullable=True),
    sa.Column('order_by', sa.String(length=50), nullable=False),
    sa.Column('limit_count', sa.Integer(), nullable=True),
    sa.Column('cache_data', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('faction_filter IS NULL OR faction_filter IN (\'Enlightened\', \'Resistance\', \'All\')', name='check_faction_filter'),
    sa.CheckConstraint('period_type IN (\'all_time\', \'monthly\', \'weekly\', \'daily\')', name='check_cache_period_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', 'faction_filter')
    )
    op.create_index(op.f('ix_leaderboard_cache_cache_key'), 'leaderboard_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_leaderboard_cache_expires_at'), 'leaderboard_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_leaderboard_cache_faction_filter'), 'leaderboard_cache', ['faction_filter'], unique=False)
    op.create_index(op.f('ix_leaderboard_cache_period_type'), 'leaderboard_cache', ['period_type'], unique=False)

    # Create faction_changes table
    op.create_table('faction_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('old_faction', sa.String(length=20), nullable=True),
    sa.Column('new_faction', sa.String(length=20), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.CheckConstraint('new_faction IN (\'Enlightened\', \'Resistance\')', name='check_new_faction'),
    sa.CheckConstraint('old_faction IN (\'Enlightened\', \'Resistance\')', name='check_old_faction'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_changes_agent_id'), 'faction_changes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_faction_changes_change_date'), 'faction_changes', ['change_date'], unique=False)

    # Create progress_snapshots table
    op.create_table('progress_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('total_ap', sa.BigInteger(), nullable=True),
    sa.Column('unique_portals_visited', sa.Integer(), nullable=True),
    sa.Column('portals_discovered', sa.Integer(), nullable=True),
    sa.Column('seer_badges', sa.Integer(), nullable=True),
    sa.Column('scout_controller_badges', sa.Integer(), nullable=True),
    sa.Column('magnetron_badges', sa.Integer(), nullable=True),
    sa.Column('hacker_badges', sa.Integer(), nullable=True),
    sa.Column('liberator_badges', sa.Integer(), nullable=True),
    sa.Column('engineer_badges', sa.Integer(), nullable=True),
    sa.Column('explorer_badges', sa.Integer(), nullable=True),
    sa.Column('pioneer_badges', sa.Integer(), nullable=True),
    sa.Column('builder_badges', sa.Integer(), nullable=True),
    sa.Column('connector_badges', sa.Integer(), nullable=True),
    sa.Column('mind_controller_badges', sa.Integer(), nullable=True),
    sa.Column('illuminator_badges', sa.Integer(), nullable=True),
    sa.Column('recharger_badges', sa.Integer(), nullable=True),
    sa.Column('purifier_badges', sa.Integer(), nullable=True),
    sa.Column('guardian_badges', sa.Integer(), nullable=True),
    sa.Column('sojourner_badges', sa.Integer(), nullable=True),
    sa.Column('trekker_badges', sa.Integer(), nullable=True),
    sa.Column('pioneer_hacker_badges', sa.Integer(), nullable=True),
    sa.Column('hacker_l4_badges', sa.Integer(), nullable=True),
    sa.Column('hacker_l5_badges', sa.Integer(), nullable=True),
    sa.Column('hacker_l6_badges', sa.Integer(), nullable=True),
    sa.Column('hacker_l7_badges', sa.Integer(), nullable=True),
    sa.Column('hacker_l8_badges', sa.Integer(), nullable=True),
    sa.Column('pioneer_hacker_l4_badges', sa.Integer(), nullable=True),
    sa.Column('pioneer_hacker_l5_badges', sa.Integer(), nullable=True),
    sa.Column('pioneer_hacker_l6_badges', sa.Integer(), nullable=True),
    sa.Column('pioneer_hacker_l7_badges', sa.Integer(), nullable=True),
    sa.Column('pioneer_hacker_l8_badges', sa.Integer(), nullable=True),
    sa.Column('spec_ops_badges', sa.Integer(), nullable=True),
    sa.Column('quantum_capsules_deployed', sa.Integer(), nullable=True),
    sa.Column('links_created', sa.Integer(), nullable=True),
    sa.Column('control_fields_created', sa.Integer(), nullable=True),
    sa.Column('mind_units_captured', sa.BigInteger(), nullable=True),
    sa.Column('longest_link_ever_created', sa.Integer(), nullable=True),
    sa.Column('largest_field_mus_ever', sa.BigInteger(), nullable=True),
    sa.Column('xm_collected', sa.BigInteger(), nullable=True),
    sa.Column('xm_recharged', sa.BigInteger(), nullable=True),
    sa.Column('distance_walked', sa.BigInteger(), nullable=True),
    sa.Column('max_time_portal_held', sa.Integer(), nullable=True),
    sa.Column('max_time_link_held', sa.Integer(), nullable=True),
    sa.Column('max_link_length', sa.Integer(), nullable=True),
    sa.Column('max_time_field_held', sa.Integer(), nullable=True),
    sa.Column('largest_field_mus', sa.BigInteger(), nullable=True),
    sa.Column('unique_missions_completed', sa.Integer(), nullable=True),
    sa.Column('missions_completed', sa.Integer(), nullable=True),
    sa.Column('mission_days_active', sa.Integer(), nullable=True),
    sa.Column('seer_points', sa.Integer(), nullable=True),
    sa.Column('scout_controlling_points', sa.Integer(), nullable=True),
    sa.Column('level_8_days', sa.Integer(), nullable=True),
    sa.Column('recursions', sa.Integer(), nullable=True),
    sa.Column('ap_gained', sa.BigInteger(), nullable=True),
    sa.Column('create_ace_badges', sa.Integer(), nullable=True),
    sa.Column('ace_deploy_badges', sa.Integer(), nullable=True),
    sa.Column('ace_recharge_badges', sa.Integer(), nullable=True),
    sa.Column('ace_link_badges', sa.Integer(), nullable=True),
    sa.Column('ace_field_badges', sa.Integer(), nullable=True),
    sa.Column('ace_invasion_badges', sa.Integer(), nullable=True),
    sa.Column('ace_resonator_badges', sa.Integer(), nullable=True),
    sa.Column('ace_mod_badges', sa.Integer(), nullable=True),
    sa.Column('ace_purify_badges', sa.Integer(), nullable=True),
    sa.Column('ace_vr_battle_badges', sa.Integer(), nullable=True),
    sa.Column('ace_vr_deploy_badges', sa.Integer(), nullable=True),
    sa.Column('ace_vr_hack_badges', sa.Integer(), nullable=True),
    sa.Column('ace_vr_link_badges', sa.Integer(), nullable=True),
    sa.Column('ace_vr_purify_badges', sa.Integer(), nullable=True),
    sa.Column('ace_vr_shield_badges', sa.Integer(), nullable=True),
    sa.Column('current_standing', sa.String(length=50), nullable=True),
    sa.Column('current_standing_date', sa.Date(), nullable=True),
    sa.Column('first_saturday_visits', sa.Integer(), nullable=True),
    sa.Column('global_resonators_score', sa.Integer(), nullable=True),
    sa.Column('global_links_score', sa.Integer(), nullable=True),
    sa.Column('global_fields_score', sa.Integer(), nullable=True),
    sa.Column('global_unique_missions_score', sa.Integer(), nullable=True),
    sa.Column('agent_level', sa.Integer(), nullable=True),
    sa.Column('agent_ap', sa.BigInteger(), nullable=True),
    sa.Column('agent_energy_gained', sa.BigInteger(), nullable=True),
    sa.Column('agent_distance_walked', sa.BigInteger(), nullable=True),
    sa.Column('agent_resonators_deployed', sa.Integer(), nullable=True),
    sa.Column('agent_links_created', sa.Integer(), nullable=True),
    sa.Column('agent_control_fields_created', sa.Integer(), nullable=True),
    sa.Column('agent_mind_units_captured', sa.BigInteger(), nullable=True),
    sa.Column('agent_longest_link_ever_created', sa.Integer(), nullable=True),
    sa.Column('agent_largest_field_mus_ever', sa.BigInteger(), nullable=True),
    sa.Column('agent_xm_recharged', sa.BigInteger(), nullable=True),
    sa.Column('agent_portals_discovered', sa.Integer(), nullable=True),
    sa.Column('agent_seer_badges', sa.Integer(), nullable=True),
    sa.Column('agent_unique_portals_visited', sa.Integer(), nullable=True),
    sa.Column('agent_max_time_portal_held', sa.Integer(), nullable=True),
    sa.Column('agent_max_time_link_held', sa.Integer(), nullable=True),
    sa.Column('agent_max_time_field_held', sa.Integer(), nullable=True),
    sa.Column('agent_purifier_badges', sa.Integer(), nullable=True),
    sa.Column('agent_hacker_badges', sa.Integer(), nullable=True),
    sa.Column('agent_builder_badges', sa.Integer(), nullable=True),
    sa.Column('agent_connector_badges', sa.Integer(), nullable=True),
    sa.Column('agent_explorer_badges', sa.Integer(), nullable=True),
    sa.Column('agent_pioneer_badges', sa.Integer(), nullable=True),
    sa.Column('agent_engineer_badges', sa.Integer(), nullable=True),
    sa.Column('agent_liberator_badges', sa.Integer(), nullable=True),
    sa.Column('agent_spec_ops_badges', sa.Integer(), nullable=True),
    sa.Column('agent_mission_days_active', sa.Integer(), nullable=True),
    sa.Column('agent_missions_completed', sa.Integer(), nullable=True),
    sa.Column('agent_recursions', sa.Integer(), nullable=True),
    sa.Column('agent_gym_badges', sa.Integer(), nullable=True),
    sa.Column('agent_trekker_badges', sa.Integer(), nullable=True),
    sa.Column('agent_recharger_badges', sa.Integer(), nullable=True),
    sa.Column('agent_sojourner_badges', sa.Integer(), nullable=True),
    sa.Column('agent_guardian_badges', sa.Integer(), nullable=True),
    sa.Column('agent_agent_level_8_days', sa.Integer(), nullable=True),
    sa.Column('agent_agent_first_saturday_visits', sa.Integer(), nullable=True),
    sa.Column('agent_agent_agent_xm_collected', sa.BigInteger(), nullable=True),
    sa.Column('agent_agent_distance_walked', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_ap', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_level', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_energy_gained', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_distance_walked', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_resonators_deployed', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_links_created', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_control_fields_created', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_mind_units_captured', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_longest_link_ever_created', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_largest_field_mus_ever', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_xm_recharged', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_portals_discovered', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_seer_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_unique_portals_visited', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_max_time_portal_held', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_max_time_link_held', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_max_time_field_held', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_purifier_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_hacker_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_builder_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_connector_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_explorer_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_pioneer_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_engineer_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_liberator_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_spec_ops_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_mission_days_active', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_missions_completed', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_recursions', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_gym_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_trekker_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_recharger_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_sojourner_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_guardian_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_agent_level_8_days', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_agent_first_saturday_visits', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_agent_agent_xm_collected', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_agent_agent_distance_walked', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_ap', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_resistance_links', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_fields', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_missions', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_resistance_unique_missions', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_ap', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_level', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_energy_gained', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_distance_walked', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_resonators_deployed', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_links_created', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_control_fields_created', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_mind_units_captured', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_longest_link_ever_created', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_largest_field_mus_ever', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_xm_recharged', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_portals_discovered', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_seer_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_unique_portals_visited', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_max_time_portal_held', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_max_time_link_held', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_max_time_field_held', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_purifier_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_hacker_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_builder_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_connector_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_explorer_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_pioneer_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_engineer_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_liberator_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_spec_ops_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_mission_days_active', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_missions_completed', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_recursions', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_gym_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_trekker_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_recharger_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_sojourner_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_guardian_badges', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_agent_level_8_days', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_agent_first_saturday_visits', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_agent_agent_xm_collected', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_agent_agent_distance_walked', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_ap', sa.BigInteger(), nullable=True),
    sa.Column('global_agent_faction_enlightened_links', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_fields', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_missions', sa.Integer(), nullable=True),
    sa.Column('global_agent_faction_enlightened_unique_missions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.CheckConstraint('snapshot_type IN (\'monthly\', \'quarterly\', \'yearly\')', name='check_snapshot_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'snapshot_date', 'snapshot_type')
    )
    op.create_index(op.f('ix_progress_snapshots_agent_id'), 'progress_snapshots', ['agent_id'], unique=False)
    op.create_index(op.f('ix_progress_snapshots_snapshot_date'), 'progress_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_progress_snapshots_snapshot_type'), 'progress_snapshots', ['snapshot_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_snapshots_snapshot_type'), table_name='progress_snapshots')
    op.drop_index(op.f('ix_progress_snapshots_snapshot_date'), table_name='progress_snapshots')
    op.drop_index(op.f('ix_progress_snapshots_agent_id'), table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index(op.f('ix_faction_changes_change_date'), table_name='faction_changes')
    op.drop_index(op.f('ix_faction_changes_agent_id'), table_name='faction_changes')
    op.drop_table('faction_changes')
    op.drop_index(op.f('ix_leaderboard_cache_period_type'), table_name='leaderboard_cache')
    op.drop_index(op.f('ix_leaderboard_cache_faction_filter'), table_name='leaderboard_cache')
    op.drop_index(op.f('ix_leaderboard_cache_expires_at'), table_name='leaderboard_cache')
    op.drop_index(op.f('ix_leaderboard_cache_cache_key'), table_name='leaderboard_cache')
    op.drop_table('leaderboard_cache')
    op.drop_index(op.f('ix_agent_stats_stats_submission_id'), table_name='agent_stats')
    op.drop_index(op.f('ix_agent_stats_stat_name'), table_name='agent_stats')
    op.drop_index(op.f('ix_agent_stats_stat_category'), table_name='agent_stats')
    op.drop_table('agent_stats')
    op.drop_index(op.f('ix_stats_submissions_period_type'), table_name='stats_submissions')
    op.drop_index(op.f('ix_stats_submissions_submission_date'), table_name='stats_submissions')
    op.drop_index(op.f('ix_stats_submissions_agent_id'), table_name='stats_submissions')
    op.drop_table('stats_submissions')
    op.drop_index(op.f('ix_agents_faction'), table_name='agents')
    op.drop_index('idx_user_agent', table_name='agents')
    op.drop_index('idx_faction', table_name='agents')
    op.drop_index('idx_agent_name', table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###